services:
  - type: web
    name: suporteai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GLPI_URL
        sync: false
      - key: GLPI_APP_TOKEN
        sync: false
      - key: GLPI_USER_TOKEN
        sync: false 